import 'package:mbh/models/Hotel.dart';
import 'package:mbh/models/Rooms.dart';

const List<Hotel> hotels = [
  const Hotel(
    id: 1,
    name: 'Hotel le Berceau',
    description: 'Hotel tropical avec un style traditionnel',
    ville: 'Notsé',
    stars: 3,
    image: 'assets/images/hotels/hotel1.jpg',
    longitude: 1.16667,
    latitude: 6.95,
  ),
  const Hotel(
    id: 2,
    name: 'Hotel de la Paix',
    description: 'Hôtel de luxe situé au cœur de la ville',
    ville: 'Kpalimé',
    stars: 4,
    image: 'assets/images/hotels/hotel2.jpg',
    longitude: 0.63333,
    latitude: 6.9,
  ),
  const Hotel(
    id: 3,
    name: 'Hotel La Roseraie',
    description: 'Hôtel romantique avec un charmant jardin',
    ville: 'Lomé',
    stars: 3,
    image: 'assets/images/hotels/hotel3.jpg',
    longitude: 1.2221,
    latitude: 6.127,
  ),
  const Hotel(
    id: 4,
    name: 'Hotel des Alpes',
    description: 'Hôtel de montagne avec vue panoramique',
    ville: 'Tsévié',
    stars: 4,
    image: 'assets/images/hotels/hotel4.jpeg',
    longitude: 1.2014,
    latitude: 6.4278,
  ),
  const Hotel(
    id: 5,
    name: 'Hotel La Belle Vie',
    description: 'Hôtel design dans un quartier branché',
    ville: 'Lomé',
    stars: 4,
    image: 'assets/images/hotels/hotel5.jpeg',
    longitude: 1.2221,
    latitude: 6.127,
  ),
  const Hotel(
    id: 6,
    name: 'Hotel le Château',
    description: 'Hôtel historique dans un cadre pittoresque',
    ville: 'Lomé',
    stars: 3,
    image: 'assets/images/hotels/hotel6.jpg',
    longitude: 1.2221,
    latitude: 6.127,
  ),
  const Hotel(
    id: 7,
    name: 'Hotel Le Mirage',
    description: 'Hôtel moderne avec des chambres spacieuses',
    ville: 'Lomé',
    stars: 4,
    image: 'assets/images/hotels/hotel7.jpeg',
    longitude: 1.2221,
    latitude: 6.127,
  ),
  const Hotel(
    id: 8,
    name: 'Hotel Le Soleil',
    description: 'Hôtel en bord de mer avec une vue imprenable',
    ville: 'Kara',
    stars: 5,
    image: 'assets/images/hotels/hotel8.jpg',
    longitude: 2.935,
    latitude: 9.551,
  ),
  const Hotel(
    id: 9,
    name: 'Hotel de la Plage',
    description:
        'Hôtel sur la plage, avec vue sur l\'océan et une grande piscine extérieure',
    ville: 'Lomé',
    stars: 4,
    image: 'assets/images/hotels/hotel9.jpg',
    longitude: 0.6333,
    latitude: 6.9000,
  ),
  const Hotel(
    id: 10,
    name: 'Hotel de la Vallée',
    description:
        'Hôtel de charme en bord de rivière, avec un grand parc et des activités en plein air',
    ville: 'Kpalimé',
    stars: 3,
    image: 'assets/images/hotels/hotel10.jpg',
    longitude: 1.1333,
    latitude: 7.5333,
  ),
  const Hotel(
    id: 11,
    name: 'Hotel du Château',
    description:
        'Hôtel historique dans un château du XVIIème siècle, avec des chambres luxueuses et un grand parc',
    ville: 'Lomé',
    stars: 5,
    image: 'assets/images/hotels/hotel11.jpg',
    longitude: 1.1333,
    latitude: 8.9833,
  ),
  const Hotel(
    id: 12,
    name: 'Hotel du Lac',
    description:
        'Hôtel romantique au bord d\'un lac, avec des chambres élégantes et un restaurant gastronomique',
    ville: 'Lomé',
    stars: 4,
    image: 'assets/images/hotels/hotel12.jpg',
    longitude: 1.32,
    latitude: 1.25,
  ),
  const Hotel(
    id: 13,
    name: 'Hotel des Montagnes',
    description:
        'Hôtel de montagne avec une vue imprenable, un spa et des activités de plein air',
    ville: 'Lomé',
    stars: 4,
    image: 'assets/images/hotels/hotel13.jpg',
    longitude: 0.4706,
    latitude: 10.3597,
  ),
  const Hotel(
    id: 14,
    name: 'Hotel de la Gare',
    description:
        'Hôtel convivial et familial, à proximité de la gare et des attractions touristiques',
    ville: 'Lomé',
    stars: 2,
    image: 'assets/images/hotels/hotel14.jpeg',
    longitude: 1.1861,
    latitude: 9.5511,
  ),
  const Hotel(
    id: 15,
    name: 'Hôtel Belle Vue',
    description:
        'Situé en bord de mer, l\'Hôtel Belle Vue offre une vue imprenable sur l\'océan.',
    ville: 'Lomé',
    stars: 4,
    image: 'assets/images/hotels/hotel15.jpg',
    longitude: 1.1861,
    latitude: 6.2333,
  ),
];

List<Hotel> popularsHotels =
    hotels.where((hotel) => hotel.stars! >= 4).toList();

List<Room> rooms = [
  const Room(
    id: 1,
    image: 'assets/images/chambres/chambre1.jpg',
    name: 'Chambre de luxe 05',
    price: 75000,
    isAvailable: true,
  ),
  const Room(
    id: 2,
    image: 'assets/images/picines/picine1.jpg',
    name: 'Picine du nord',
    price: 75000,
    isAvailable: true,
  ),
  const Room(
    id: 3,
    image: 'assets/images/chambres/chambre2.jpg',
    name: 'Chambre 2',
    price: 75000,
    isAvailable: true,
  ),
  const Room(
    id: 4,
    image: 'assets/images/chambres/chambre3.jpg',
    name: 'Chambre 08',
    price: 75000,
    isAvailable: true,
  ),
  const Room(
    id: 5,
    image: 'assets/images/picines/picine2.jpg',
    name: 'Picine à l\entrée',
    price: 75000,
    isAvailable: true,
  ),
  const Room(
    id: 6,
    image: 'assets/images/chambres/chambre4.jpeg',
    price: 75000,
    name: 'Chambre 11',
    isAvailable: false,
  ),
  const Room(
    id: 7,
    image: 'assets/images/chambres/chambre5.jpg',
    price: 75000,
    name: 'Chambre 15',
    isAvailable: true,
  ),
  const Room(
    id: 8,
    image: 'assets/images/chambres/chambre6.jpg',
    name: 'Chambre 17',
    price: 75000,
    isAvailable: true,
  ),
  const Room(
    id: 9,
    image: 'assets/images/chambres/chambre7.jpg',
    name: 'Chambre de luxe 12',
    price: 75000,
    isAvailable: false,
  ),
  const Room(
    id: 10,
    image: 'assets/images/picines/picine3.jpg',
    price: 75000,
    name: 'Picine du sud',
    isAvailable: true,
  ),
  const Room(
    id: 11,
    image: 'assets/images/chambres/chambre9.jpeg',
    name: 'Chambre pour deux 67',
    price: 75000,
    isAvailable: true,
  ),
];

List<Hotel> nearsHotels =
    hotels.where((hotel) => hotel.ville == 'Lomé').toList();
List<Hotel> favoritesHotels = popularsHotels;
